-- Steel Challenge production schema.
-- Safe to run after the prototype schema: legacy columns are preserved.

begin;

create extension if not exists pgcrypto;
create schema if not exists private;

create table if not exists public.profiles (
    id uuid primary key default gen_random_uuid(),
    auth_user_id uuid not null unique references auth.users(id) on delete cascade,
    email text not null unique,
    display_name text,
    approved boolean not null default false,
    can_view boolean not null default false,
    can_download boolean not null default false,
    is_admin boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.email_messages (
    id bigint generated by default as identity primary key,
    gmail_message_id text not null unique,
    gmail_thread_id text,
    sender_name text,
    sender_email text,
    subject text,
    email_received_at timestamptz,
    parsed_status text not null default 'processing',
    parser_source text,
    parser_error text,
    raw_excerpt text,
    duplicate_skip_count integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint email_messages_parsed_status_check
        check (parsed_status in ('processing', 'success', 'failed'))
);

create table if not exists public.runs (
    id bigint generated by default as identity primary key,
    email_message_id bigint references public.email_messages(id) on delete set null,
    source_run_index integer not null default 1,
    source text not null default 'docx',
    created_by uuid references auth.users(id) on delete set null,
    sender_name text,
    sender_email text,
    steel_user_id text,
    process_type text,
    run_date timestamptz,
    status integer,
    score double precision,
    user_level text,
    steel_grade text,
    time_minutes double precision,
    tapping_mass double precision,
    tap_temperature double precision,
    total_energy_kwh double precision,
    energy_kwh_per_t double precision,
    power_cost double precision,
    scrap_cost double precision,
    additions_cost double precision,
    other_consumables_cost double precision,
    total_cost double precision,
    cost_per_tonne double precision,
    uploader text,
    file_name text,
    data_json jsonb not null default '{}'::jsonb,
    uploaded_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    constraint runs_source_check check (source in ('gmail', 'docx')),
    constraint runs_data_json_object_check check (jsonb_typeof(data_json) = 'object')
);

-- Columns needed when upgrading the existing prototype table.
alter table public.runs add column if not exists email_message_id bigint;
alter table public.runs add column if not exists source_run_index integer default 1;
alter table public.runs add column if not exists source text default 'docx';
alter table public.runs add column if not exists created_by uuid;
alter table public.runs add column if not exists sender_name text;
alter table public.runs add column if not exists sender_email text;
alter table public.runs add column if not exists steel_user_id text;
alter table public.runs add column if not exists process_type text;
alter table public.runs add column if not exists run_date timestamptz;
alter table public.runs add column if not exists status integer;
alter table public.runs add column if not exists score double precision;
alter table public.runs add column if not exists user_level text;
alter table public.runs add column if not exists steel_grade text;
alter table public.runs add column if not exists time_minutes double precision;
alter table public.runs add column if not exists tapping_mass double precision;
alter table public.runs add column if not exists tap_temperature double precision;
alter table public.runs add column if not exists total_energy_kwh double precision;
alter table public.runs add column if not exists energy_kwh_per_t double precision;
alter table public.runs add column if not exists power_cost double precision;
alter table public.runs add column if not exists scrap_cost double precision;
alter table public.runs add column if not exists additions_cost double precision;
alter table public.runs add column if not exists other_consumables_cost double precision;
alter table public.runs add column if not exists total_cost double precision;
alter table public.runs add column if not exists cost_per_tonne double precision;
alter table public.runs add column if not exists uploader text;
alter table public.runs add column if not exists file_name text;
alter table public.runs add column if not exists data_json jsonb default '{}'::jsonb;
alter table public.runs add column if not exists uploaded_at timestamptz default now();
alter table public.runs add column if not exists created_at timestamptz;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'runs_email_message_id_fkey'
          and conrelid = 'public.runs'::regclass
    ) then
        alter table public.runs
            add constraint runs_email_message_id_fkey
            foreign key (email_message_id)
            references public.email_messages(id)
            on delete set null;
    end if;
    if not exists (
        select 1 from pg_constraint
        where conname = 'runs_created_by_fkey'
          and conrelid = 'public.runs'::regclass
    ) then
        alter table public.runs
            add constraint runs_created_by_fkey
            foreign key (created_by)
            references auth.users(id)
            on delete set null;
    end if;
end $$;

create table if not exists public.logs (
    id bigint generated by default as identity primary key,
    run_id bigint not null references public.runs(id) on delete cascade,
    log_no integer not null,
    time text,
    event_time text,
    event_seconds double precision,
    event text not null,
    category text,
    created_at timestamptz not null default now()
);

alter table public.logs add column if not exists time text;
alter table public.logs add column if not exists event_time text;
alter table public.logs add column if not exists event_seconds double precision;
alter table public.logs add column if not exists category text;
alter table public.logs add column if not exists created_at timestamptz default now();

update public.logs
set event_time = time
where event_time is null and time is not null;

update public.runs
set source = coalesce(source, 'docx'),
    data_json = coalesce(data_json, '{}'::jsonb),
    created_at = coalesce(created_at, uploaded_at, now());

alter table public.runs alter column created_at set default now();
alter table public.runs alter column created_at set not null;
alter table public.runs alter column source set default 'docx';
alter table public.runs alter column source set not null;
alter table public.runs alter column data_json set default '{}'::jsonb;
alter table public.runs alter column data_json set not null;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'runs_source_check'
          and conrelid = 'public.runs'::regclass
    ) then
        alter table public.runs
            add constraint runs_source_check check (source in ('gmail', 'docx'));
    end if;
    if not exists (
        select 1 from pg_constraint
        where conname = 'runs_data_json_object_check'
          and conrelid = 'public.runs'::regclass
    ) then
        alter table public.runs
            add constraint runs_data_json_object_check
            check (jsonb_typeof(data_json) = 'object');
    end if;
end $$;

-- Backfill direct columns so legacy JSON rows participate in filtering/KPIs.
update public.runs as r
set steel_user_id = coalesce(steel_user_id, data_json ->> 'Run Information > User Id'),
    process_type = coalesce(
        process_type,
        data_json ->> 'Run Information > Process Type',
        case
            when email_message_id is not null then (
                select case
                    when e.subject ilike '%secondary steelmaking%'
                        then 'Secondary Steelmaking'
                    else 'Electric Arc Furnace'
                end
                from public.email_messages e
                where e.id = r.email_message_id
            )
        end
    ),
    status = coalesce(
        status,
        case when data_json ->> 'Run Information > Status' ~ '^[-+]?[0-9]+$'
             then (data_json ->> 'Run Information > Status')::integer end
    ),
    score = coalesce(
        score,
        case when data_json ->> 'Run Information > Score' ~ '^[-+]?[0-9]+([.][0-9]+)?$'
             then (data_json ->> 'Run Information > Score')::double precision end
    ),
    user_level = coalesce(user_level, data_json ->> 'Simulation Settings > User Level'),
    steel_grade = coalesce(steel_grade, data_json ->> 'Simulation Settings > Steel Grade'),
    time_minutes = coalesce(
        time_minutes,
        case when data_json ->> 'Cost Breakdown > Time (in minutes)' ~ '^[-+]?[0-9]+([.][0-9]+)?$'
             then (data_json ->> 'Cost Breakdown > Time (in minutes)')::double precision end
    ),
    tapping_mass = coalesce(
        tapping_mass,
        case when data_json ->> 'Cost Breakdown > Tapping mass' ~ '^[-+]?[0-9]+([.][0-9]+)?$'
             then (data_json ->> 'Cost Breakdown > Tapping mass')::double precision end
    ),
    tap_temperature = coalesce(
        tap_temperature,
        case when data_json ->> 'Cost Breakdown > Tap temperature' ~ '^[-+]?[0-9]+([.][0-9]+)?$'
             then (data_json ->> 'Cost Breakdown > Tap temperature')::double precision end
    ),
    total_energy_kwh = coalesce(
        total_energy_kwh,
        case when data_json ->> 'Cost Breakdown > Total Energy' ~ '^[-+]?[0-9]+([.][0-9]+)?$'
             then (data_json ->> 'Cost Breakdown > Total Energy')::double precision end
    ),
    energy_kwh_per_t = coalesce(
        energy_kwh_per_t,
        case when data_json ->> 'Cost Breakdown > Total Energy_2' ~ '^[-+]?[0-9]+([.][0-9]+)?$'
             then (data_json ->> 'Cost Breakdown > Total Energy_2')::double precision end
    ),
    power_cost = coalesce(
        power_cost,
        case when data_json ->> 'Cost Breakdown > Power' ~ '^[-+]?[0-9]+([.][0-9]+)?$'
             then (data_json ->> 'Cost Breakdown > Power')::double precision end
    ),
    scrap_cost = coalesce(
        scrap_cost,
        case when data_json ->> 'Cost Breakdown > Scrap' ~ '^[-+]?[0-9]+([.][0-9]+)?$'
             then (data_json ->> 'Cost Breakdown > Scrap')::double precision end
    ),
    additions_cost = coalesce(
        additions_cost,
        case when data_json ->> 'Cost Breakdown > Additions' ~ '^[-+]?[0-9]+([.][0-9]+)?$'
             then (data_json ->> 'Cost Breakdown > Additions')::double precision end
    ),
    other_consumables_cost = coalesce(
        other_consumables_cost,
        case when data_json ->> 'Cost Breakdown > Other consumables' ~ '^[-+]?[0-9]+([.][0-9]+)?$'
             then (data_json ->> 'Cost Breakdown > Other consumables')::double precision end
    ),
    total_cost = coalesce(
        total_cost,
        case when data_json ->> 'Cost Breakdown > Total Cost' ~ '^[-+]?[0-9]+([.][0-9]+)?$'
             then (data_json ->> 'Cost Breakdown > Total Cost')::double precision end
    ),
    cost_per_tonne = coalesce(
        cost_per_tonne,
        case when data_json ->> 'Cost Breakdown > Cost Per Tonne' ~ '^[-+]?[0-9]+([.][0-9]+)?$'
             then (data_json ->> 'Cost Breakdown > Cost Per Tonne')::double precision end
    );

update public.runs
set run_date = (
    to_timestamp(data_json ->> 'Run Information > Date', 'DD/MM/YYYY HH24:MI:SS')::timestamp
    at time zone 'Asia/Seoul'
)
where run_date is null
  and coalesce(data_json ->> 'Run Information > Date', '')
      ~ '^\d{2}/\d{2}/\d{4} \d{2}:\d{2}:\d{2}$';

update public.runs
set source_run_index = 1
where source_run_index is null or source_run_index < 1;

alter table public.runs alter column source_run_index set default 1;
alter table public.runs alter column source_run_index set not null;

drop index if exists public.runs_email_message_id_unique_idx;
create unique index if not exists runs_email_message_source_run_unique_idx
    on public.runs(email_message_id, source_run_index)
    where email_message_id is not null;
create index if not exists runs_run_date_idx on public.runs(run_date desc);
create index if not exists runs_process_type_idx on public.runs(process_type);
create index if not exists runs_steel_grade_idx on public.runs(steel_grade);
create index if not exists runs_steel_user_id_idx on public.runs(steel_user_id);
create index if not exists runs_sender_email_idx on public.runs(sender_email);
create index if not exists runs_score_idx on public.runs(score);
create index if not exists runs_cost_per_tonne_idx on public.runs(cost_per_tonne);
create index if not exists runs_created_by_idx on public.runs(created_by);
create index if not exists logs_run_id_event_seconds_idx
    on public.logs(run_id, event_seconds, log_no);
create unique index if not exists logs_run_id_log_no_unique_idx
    on public.logs(run_id, log_no);
create index if not exists email_messages_status_received_idx
    on public.email_messages(parsed_status, email_received_at desc);

create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function private.set_updated_at();

drop trigger if exists email_messages_set_updated_at on public.email_messages;
create trigger email_messages_set_updated_at
before update on public.email_messages
for each row execute function private.set_updated_at();

create or replace function private.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    insert into public.profiles (auth_user_id, email, display_name)
    values (
        new.id,
        new.email,
        coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1))
    )
    on conflict (auth_user_id) do update
        set email = excluded.email,
            updated_at = now();
    return new;
end;
$$;

-- Remove only the legacy trigger created by an earlier version of this project;
-- never overwrite an unrelated generic Supabase auth trigger.
do $$
begin
    if exists (
        select 1 from pg_trigger
        where tgname = 'on_auth_user_created'
          and tgrelid = 'auth.users'::regclass
          and tgfoid = 'private.handle_new_auth_user()'::regprocedure
    ) then
        drop trigger on_auth_user_created on auth.users;
    end if;
end $$;

drop trigger if exists steel_challenge_profile_sync on auth.users;
create trigger steel_challenge_profile_sync
after insert or update of email on auth.users
for each row execute function private.handle_new_auth_user();

-- Backfill profiles for Auth users created before this migration.
insert into public.profiles (auth_user_id, email, display_name)
select id, email, coalesce(raw_user_meta_data ->> 'display_name', split_part(email, '@', 1))
from auth.users
where email is not null
on conflict (auth_user_id) do nothing;

-- One transaction for a run and all of its event logs. RLS still applies.
create or replace function public.save_run_with_logs(
    run_payload jsonb,
    log_payload jsonb default '[]'::jsonb
)
returns bigint
language plpgsql
security invoker
set search_path = ''
as $$
declare
    new_run_id bigint;
    item jsonb;
begin
    if jsonb_typeof(run_payload) <> 'object' then
        raise exception 'run_payload must be a JSON object';
    end if;
    if jsonb_typeof(coalesce(log_payload, '[]'::jsonb)) <> 'array' then
        raise exception 'log_payload must be a JSON array';
    end if;

    insert into public.runs (
        email_message_id, source_run_index, source, created_by, sender_name, sender_email,
        steel_user_id, process_type, run_date, status, score, user_level, steel_grade,
        time_minutes, tapping_mass, tap_temperature, total_energy_kwh,
        energy_kwh_per_t, power_cost, scrap_cost, additions_cost,
        other_consumables_cost, total_cost, cost_per_tonne,
        uploader, file_name, data_json
    ) values (
        nullif(run_payload ->> 'email_message_id', '')::bigint,
        coalesce(nullif(run_payload ->> 'source_run_index', '')::integer, 1),
        coalesce(nullif(run_payload ->> 'source', ''), 'docx'),
        (select auth.uid()),
        run_payload ->> 'sender_name',
        run_payload ->> 'sender_email',
        run_payload ->> 'steel_user_id',
        run_payload ->> 'process_type',
        nullif(run_payload ->> 'run_date', '')::timestamptz,
        nullif(run_payload ->> 'status', '')::integer,
        nullif(run_payload ->> 'score', '')::double precision,
        run_payload ->> 'user_level',
        run_payload ->> 'steel_grade',
        nullif(run_payload ->> 'time_minutes', '')::double precision,
        nullif(run_payload ->> 'tapping_mass', '')::double precision,
        nullif(run_payload ->> 'tap_temperature', '')::double precision,
        nullif(run_payload ->> 'total_energy_kwh', '')::double precision,
        nullif(run_payload ->> 'energy_kwh_per_t', '')::double precision,
        nullif(run_payload ->> 'power_cost', '')::double precision,
        nullif(run_payload ->> 'scrap_cost', '')::double precision,
        nullif(run_payload ->> 'additions_cost', '')::double precision,
        nullif(run_payload ->> 'other_consumables_cost', '')::double precision,
        nullif(run_payload ->> 'total_cost', '')::double precision,
        nullif(run_payload ->> 'cost_per_tonne', '')::double precision,
        run_payload ->> 'uploader',
        run_payload ->> 'file_name',
        coalesce(run_payload -> 'data_json', '{}'::jsonb)
    ) returning id into new_run_id;

    for item in select value from jsonb_array_elements(coalesce(log_payload, '[]'::jsonb))
    loop
        insert into public.logs (
            run_id, log_no, time, event_time, event_seconds, event, category
        ) values (
            new_run_id,
            (item ->> 'log_no')::integer,
            coalesce(item ->> 'time', item ->> 'event_time'),
            coalesce(item ->> 'event_time', item ->> 'time'),
            nullif(item ->> 'event_seconds', '')::double precision,
            item ->> 'event',
            item ->> 'category'
        );
    end loop;

    return new_run_id;
end;
$$;

-- Replace all runs from one Gmail message in a single transaction.  If any
-- run or log fails validation, PostgreSQL rolls back the delete and inserts.
create or replace function public.replace_email_runs_with_logs(
    p_email_message_id bigint,
    run_entries jsonb
)
returns bigint[]
language plpgsql
security invoker
set search_path = ''
as $$
declare
    entry jsonb;
    run_payload jsonb;
    new_run_id bigint;
    saved_ids bigint[] := array[]::bigint[];
begin
    if p_email_message_id is null then
        raise exception 'p_email_message_id is required';
    end if;
    if jsonb_typeof(run_entries) <> 'array' then
        raise exception 'run_entries must be a JSON array';
    end if;
    if jsonb_array_length(run_entries) < 1 then
        raise exception 'run_entries must not be empty';
    end if;

    if not exists (
        select 1 from public.email_messages where id = p_email_message_id
    ) then
        raise exception 'email_message_id % does not exist', p_email_message_id;
    end if;

    delete from public.runs where email_message_id = p_email_message_id;

    for entry in select value from jsonb_array_elements(run_entries)
    loop
        run_payload := coalesce(entry -> 'run_payload', '{}'::jsonb)
            || jsonb_build_object('email_message_id', p_email_message_id);
        if coalesce(nullif(run_payload ->> 'source_run_index', '')::integer, 0) < 1 then
            raise exception 'source_run_index must be at least 1';
        end if;
        new_run_id := public.save_run_with_logs(
            run_payload,
            coalesce(entry -> 'log_payload', '[]'::jsonb)
        );
        saved_ids := array_append(saved_ids, new_run_id);
    end loop;

    return saved_ids;
end;
$$;

notify pgrst, 'reload schema';

-- Small server-side aggregates keep the dashboard responsive as the tables grow.
-- SECURITY INVOKER deliberately preserves runs/email_messages RLS.
drop function if exists public.dashboard_metrics(
    timestamptz, timestamptz, text, text, text, integer
);
create or replace function public.dashboard_metrics(
    p_date_from timestamptz default null,
    p_date_to timestamptz default null,
    p_process_type text default null,
    p_steel_grade text default null,
    p_steel_user_id text default null,
    p_sender_email text default null,
    p_status integer default null
)
returns table (
    total_runs bigint,
    participant_count bigint,
    average_cost double precision,
    best_cost double precision,
    average_process_time double precision
)
language sql
stable
security invoker
set search_path = ''
as $$
    select
        count(*)::bigint,
        count(distinct r.steel_user_id)::bigint,
        avg(r.cost_per_tonne)::double precision,
        min(r.cost_per_tonne)::double precision,
        avg(r.time_minutes)::double precision
    from public.runs r
    where (p_date_from is null or r.run_date >= p_date_from)
      and (p_date_to is null or r.run_date <= p_date_to)
      and (p_process_type is null or r.process_type = p_process_type)
      and (p_steel_grade is null or r.steel_grade = p_steel_grade)
      and (p_steel_user_id is null or r.steel_user_id = p_steel_user_id)
      and (p_sender_email is null or r.sender_email = p_sender_email)
      and (p_status is null or r.status = p_status);
$$;

create or replace function public.data_quality_metrics()
returns table (
    total_emails bigint,
    parsed_success bigint,
    parsed_failed bigint,
    duplicate_skips bigint,
    saved_runs bigint,
    runs_without_logs bigint,
    missing_steel_grade bigint,
    missing_run_date bigint
)
language sql
stable
security invoker
set search_path = ''
as $$
    select
        (select count(*) from public.email_messages)::bigint,
        (select count(*) from public.email_messages where parsed_status = 'success')::bigint,
        (select count(*) from public.email_messages where parsed_status = 'failed')::bigint,
        (select coalesce(sum(duplicate_skip_count), 0) from public.email_messages)::bigint,
        (select count(*) from public.runs)::bigint,
        (
            select count(*) from public.runs r
            where not exists (select 1 from public.logs l where l.run_id = r.id)
        )::bigint,
        (select count(*) from public.runs where steel_grade is null or btrim(steel_grade) = '')::bigint,
        (select count(*) from public.runs where run_date is null)::bigint;
$$;

commit;
